# Generated by Django 4.2.14 on 2024-08-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='genre',
            field=models.CharField(default='Unknown', max_length=120),
            preserve_default=False,
        ),
    ]
